[package]
name = "dope_world"
version = "0.1.0"

# [tool.dojo.world]
# name = "Dope World"
# description = "Dope World"
# icon_uri = "file://assets/icon.png"
# cover_uri = "file://assets/cover.png"
# socials.x = "https://x.com/TheDopeWars"


[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0-alpha.0" }
token = { git = "https://github.com/dojoengine/origami", tag = "v0.6.0-alpha.0" }

[scripts]
katana_msg = "katana --messaging anvil.messaging.json --dev"
migrate = "sozo build && sozo migrate && ./scripts/initialize.sh local"

get_balance = "sozo model get ERC20BalanceModel 0x158be17c8c09dd5d1942c2730d72beb3d0aeb48b61d6b18505fa65ff4b0e84 0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03 --world 0x45400733b6ba466b4742f41ff0f31d55476c750c718ff141842afba499fccd2 --rpc-url http://localhost:5050"
withdraw = "sozo execute -c 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266,0x3635c9adc5dea00000,0 0x6499c1ec432db1ab906479d8c4f13125636b3939ef36b6f3fc0b09c3e499734 initiate_withdrawal"

[tool.dojo.env]
# Katana
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
rpc_url = "http://localhost:5050"

[[target.dojo]]
build-external-contracts = [
    "token::components::security::initializable::initializable_model",
    "token::components::token::erc20::erc20_metadata::erc_20_metadata_model",
    "token::components::token::erc20::erc20_balance::erc_20_balance_model",
    "token::components::token::erc20::erc20_allowance::erc_20_allowance_model",
    "token::components::token::erc20::erc20_mintable::erc_20_mintable_model",
    "token::components::token::erc20::erc20_burnable::erc_20_burnable_model",
    "token::components::token::erc20::erc20_bridgeable::erc_20_bridgeable_model",
]
