[profile.default]
solc-version = "0.8.13"
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./logs"}]
remappings = [
    "@forge-std/=lib/forge-std/src/",
    "@create3-factory/=lib/create3-factory/src/",
    "@openzeppelin/=lib/@openzeppelin/",
    "@starknet/=lib/starknet/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


# since the foundry.toml is commited it's not recommened to have the api key explicitly
# [rpc_endpoints]
# local = "${ETH_RPC_URL}"

